In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt


In [2]:
df=pd.read_csv('train_hr.csv',header=0)

In [3]:
df.head(20)

employee_id         department     region         education gender  \
0         65438  Sales & Marketing   region_7  Master's & above      f   
1         65141         Operations  region_22        Bachelor's      m   
2          7513  Sales & Marketing  region_19        Bachelor's      m   
3          2542  Sales & Marketing  region_23        Bachelor's      m   
4         48945         Technology  region_26        Bachelor's      m   
5         58896          Analytics   region_2        Bachelor's      m   
6         20379         Operations  region_20        Bachelor's      f   
7         16290         Operations  region_34  Master's & above      m   
8         73202          Analytics  region_20        Bachelor's      m   
9         28911  Sales & Marketing   region_1  Master's & above      m   
10        29934         Technology  region_23               NaN      m   
11        49017  Sales & Marketing   region_7        Bachelor's      f   
12        60051  Sales & Marketing   region_4        Bachelor's      m   
13        38401         Technology  region_29  Master's & above      m   
14        77040                R&D   region_2  Master's & above      m   
15        43931         Operations   region_7        Bachelor's      m   
16         7152         Technology   region_2        Bachelor's      m   
17         9403  Sales & Marketing  region_31        Bachelor's      m   
18        17436  Sales & Marketing  region_31        Bachelor's      m   
19        54461         Operations  region_15        Bachelor's      m   

   recruitment_channel  no_of_trainings  age  previous_year_rating  \
0             sourcing                1   35                   5.0   
1                other                1   30                   5.0   
2             sourcing                1   34                   3.0   
3                other                2   39                   1.0   
4                other                1   45                   3.0   
5             sourcing                2   31                   3.0   
6                other                1   31                   3.0   
7             sourcing                1   33                   3.0   
8                other                1   28                   4.0   
9             sourcing                1   32                   5.0   
10            sourcing                1   30                   NaN   
11            sourcing                1   35                   5.0   
12            sourcing                1   49                   5.0   
13               other                2   39                   3.0   
14            sourcing                1   37                   3.0   
15               other                1   37                   1.0   
16               other                1   38                   3.0   
17               other                1   34                   1.0   
18               other                1   34                   5.0   
19               other                1   37                   3.0   

    length_of_service  KPIs_met >80%  awards_won?  avg_training_score  \
0                   8              1            0                  49   
1                   4              0            0                  60   
2                   7              0            0                  50   
3                  10              0            0                  50   
4                   2              0            0                  73   
5                   7              0            0                  85   
6                   5              0            0                  59   
7                   6              0            0                  63   
8                   5              0            0                  83   
9                   5              1            0                  54   
10                  1              0            0                  77   
11                  3              1            0                  50   
12                  5        

In [4]:
df.columns

Index(['employee_id', 'department', 'region', 'education', 'gender',
       'recruitment_channel', 'no_of_trainings', 'age', 'previous_year_rating',
       'length_of_service', 'KPIs_met >80%', 'awards_won?',
       'avg_training_score', 'is_promoted'],
      dtype='object')

In [26]:
df.isnull().sum()

employee_id             0
department              0
region                  0
education               0
gender                  0
recruitment_channel     0
no_of_trainings         0
age                     0
previous_year_rating    0
length_of_service       0
KPIs_met >80%           0
awards_won?             0
avg_training_score      0
is_promoted             0
dtype: int64

In [7]:
x=df.iloc[0:11]
y=df.iloc[:,:-1]

In [7]:
df['education'].value_counts()

Bachelor's          36669
Master's & above    14925
Below Secondary       805
Name: education, dtype: int64

In [8]:
y

employee_id         department     region         education gender  \
0            65438  Sales & Marketing   region_7  Master's & above      f   
1            65141         Operations  region_22        Bachelor's      m   
2             7513  Sales & Marketing  region_19        Bachelor's      m   
3             2542  Sales & Marketing  region_23        Bachelor's      m   
4            48945         Technology  region_26        Bachelor's      m   
...            ...                ...        ...               ...    ...   
54803         3030         Technology  region_14        Bachelor's      m   
54804        74592         Operations  region_27  Master's & above      f   
54805        13918          Analytics   region_1        Bachelor's      m   
54806        13614  Sales & Marketing   region_9               NaN      m   
54807        51526                 HR  region_22        Bachelor's      m   

      recruitment_channel  no_of_trainings  age  previous_year_rating  \
0                sourcing                1   35                   5.0   
1                   other                1   30                   5.0   
2                sourcing                1   34                   3.0   
3                   other                2   39                   1.0   
4                   other                1   45                   3.0   
...                   ...              ...  ...                   ...   
54803            sourcing                1   48                   3.0   
54804               other                1   37                   2.0   
54805               other                1   27                   5.0   
54806            sourcing                1   29                   1.0   
54807               other                1   27                   1.0   

       length_of_service  KPIs_met >80%  awards_won?  avg_training_score  
0                      8              1            0                  49  
1                      4              0            0                  60  
2                      7              0            0                  50  
3                     10              0            0                  50  
4                      2              0            0                  73  
...                  ...            ...          ...                 ...  
54803                 17              0            0                  78  
54804                  6              0            0                  56  
54805                  3              1            0                  79  
54806                  2              0            0                  45  
54807                  5              0            0                  49  

[54808 rows x 13 columns]

In [8]:
df['previous_year_rating'].value_counts()

3.0    18618
5.0    11741
4.0     9877
1.0     6223
2.0     4225
Name: previous_year_rating, dtype: int64

In [23]:
df['education'].fillna(df['education'].mode()[0],inplace=True)

In [25]:
df['previous_year_rating'].fillna(df['previous_year_rating'].mode()[0],inplace=True)

In [31]:
colname=[]
for x in df.columns:
    if df[x].dtype == 'object':
        colname.append(x)
colname        
    
    

['department', 'region', 'education', 'gender', 'recruitment_channel']

In [32]:
from sklearn.preprocessing import LabelEncoder

In [33]:
lm=LabelEncoder()

In [35]:
for x in colname:
    df[x]=lm.fit_transform(df[x])

In [36]:
X=df.values[:,:-1]
Y=df.values[:,-1]

In [37]:
X

array([[6.5438e+04, 7.0000e+00, 3.1000e+01, ..., 1.0000e+00, 0.0000e+00,
        4.9000e+01],
       [6.5141e+04, 4.0000e+00, 1.4000e+01, ..., 0.0000e+00, 0.0000e+00,
        6.0000e+01],
       [7.5130e+03, 7.0000e+00, 1.0000e+01, ..., 0.0000e+00, 0.0000e+00,
        5.0000e+01],
       ...,
       [1.3918e+04, 0.0000e+00, 0.0000e+00, ..., 1.0000e+00, 0.0000e+00,
        7.9000e+01],
       [1.3614e+04, 7.0000e+00, 3.3000e+01, ..., 0.0000e+00, 0.0000e+00,
        4.5000e+01],
       [5.1526e+04, 2.0000e+00, 1.4000e+01, ..., 0.0000e+00, 0.0000e+00,
        4.9000e+01]])

In [38]:
from sklearn.preprocessing import StandardScaler

In [39]:
sc=StandardScaler()

In [40]:
sc.fit(X)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [41]:
ash=sc.transform(X)

In [42]:
ash

array([[ 1.16185837,  0.80893285,  1.77652645, ...,  1.35687789,
        -0.15401776, -1.07593145],
       [ 1.14870885, -0.38818322, -0.16303375, ..., -0.73698599,
        -0.15401776, -0.25328242],
       [-1.40274081,  0.80893285, -0.61940086, ..., -0.73698599,
        -0.15401776, -1.00114517],
       ...,
       [-1.11916278, -1.98433798, -1.76031862, ...,  1.35687789,
        -0.15401776,  1.1676568 ],
       [-1.13262222,  0.80893285,  2.00471   , ..., -0.73698599,
        -0.15401776, -1.37507655],
       [ 0.54591182, -1.1862606 , -0.16303375, ..., -0.73698599,
        -0.15401776, -1.07593145]])

In [43]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=10)

In [44]:
from sklearn.linear_model import LogisticRegression

In [45]:
lmr =LogisticRegression()

In [46]:
lmr.fit(X_train,Y_train)

C:\Users\Ashish\Downloads\anaconda\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [47]:
Y_pred=lmr.predict(X_test)

In [49]:
Y_pred

array([0., 0., 0., ..., 0., 0., 0.])

In [50]:
print(lmr.coef_)

[[-7.72948636e-06 -1.79266507e-02 -1.92635346e-02  4.64579541e-03
  -3.43278616e-03 -3.43047418e-03 -7.12140769e-03 -7.58967024e-02
   7.45013286e-03  1.63678016e-03  1.01977230e-02  3.29429774e-03
   1.40188846e-02]]


In [51]:
print(lmr.intercept_)

[-0.00407359]


In [61]:
from sklearn.metrics import confusion_matrix 
print('confusion matrix:')
confusion_matrix(Y_test,Y_pred)

confusion matrix:


array([[15064,     0],
       [ 1379,     0]], dtype=int64)

In [62]:
from sklearn.metrics import classification_report
print('classification report:')
print(classification_report(Y_test,Y_pred))


classification report:
              precision    recall  f1-score   support

         0.0       0.92      1.00      0.96     15064
         1.0       0.00      0.00      0.00      1379

   micro avg       0.92      0.92      0.92     16443
   macro avg       0.46      0.50      0.48     16443
weighted avg       0.84      0.92      0.88     16443



C:\Users\Ashish\Downloads\anaconda\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [60]:
from sklearn.metrics import accuracy_score
print('accuracy:')
accuracy_score(Y_test,Y_pred)

accuracy:


0.9161345253299277